# Generated by Django 3.0.5 on 2020-06-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20200623_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='deck',
            name='subject',
            field=models.CharField(max_length=40),
        ),
    ]
