# Generated by Django 3.0.4 on 2020-03-13 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20200310_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='cards',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.Deck'),
            preserve_default=False,
        ),
    ]
