# Generated by Django 3.0.4 on 2020-03-13 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20200313_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cards',
            field=models.ForeignKey(default='cards', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.Deck'),
        ),
    ]
