# Generated by Django 3.1.2 on 2020-11-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20200626_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
