# Generated by Django 3.0.4 on 2020-03-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_auto_20200314_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answertick', models.BooleanField()),
            ],
        ),
    ]
