# Generated by Django 3.0.5 on 2020-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_auto_20200315_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(default='Add a Description', max_length=300),
        ),
    ]
